services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: isommelier_db
      POSTGRES_USER: isommelier_user
      POSTGRES_PASSWORD: Aline231
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:


